_errors:
    path: /{_locale}/_error/{code}.{_format}
    requirements:
        code : "\\d+"
    defaults:
        _controller: "twig.controller.preview_error::previewErrorPageAction"
        _format : "html"
    options: { i18n: false }