index:
    path: /{trailingSlash}
    controller: App\Controller\SimplePageController::index
    requirements:
        trailingSlash : "[/]{0,1}"
    defaults:
        trailingSlash : "/"

root:
    path: /
    controller: App\Controller\SimplePageController::index
    options: { i18n: false }

imprint:
    path: /imprint
    controller: App\Controller\SimplePageController::such

transparency:
    path: /transparency
    controller: App\Controller\SimplePageController::such

charter:
    path: /charter
    controller: App\Controller\SimplePageController::such
