index:
    path: /{trailingSlash}
    controller: App\Controller\IndexController::index
    requirements:
        trailingSlash : "[/]{0,1}"
    defaults:
        trailingSlash : "/"

root:
    path: /{_locale}
    controller: App\Controller\IndexController::index
    defaults:
        _locale: '%locale%'
    options: { i18n: false }

imprint:
    path: /imprint
    controller: App\Controller\SimplePageController::imprint

transparency:
    path: /transparency
    controller: App\Controller\SimplePageController::transparency

charter:
    path: /charter
    controller: App\Controller\SimplePageController::charter

themes:
    path: /themes
    controller: App\Controller\TemplatesController::previewTopics

# for previewing purposes only
themesLegacy:
    path: /templates/pages/topics-draft
    controller: App\Controller\TemplatesController::previewTopics

peopleStaff:
    path: /people/staff
    controller: App\Controller\PeopleController::staff

# for previewing purposes only
peopleLegacy:
    path: /templates/pages/team-draft
    controller: App\Controller\TemplatesController::previewTeam

# templates:
#     path: /templates{path}
#     controller: App\Controller\TemplatesController::preview
#     # allow slashes in route parameters, see
#     # https://symfony.com/doc/current/routing/slash_in_parameter.html
#     requirements:
#         path: .+
