index:
    path: /{trailingSlash}
    controller: App\Controller\IndexController::index
    requirements:
        trailingSlash : "[/]{0,1}"
    defaults:
        trailingSlash : "/"

root:
    path: /{_locale}
    controller: App\Controller\IndexController::index
    defaults:
        _locale: '%locale%'
    options: { i18n: false }

imprint:
    path: /imprint
    controller: App\Controller\SimplePageController::imprint

transparency:
    path: /transparency
    controller: App\Controller\SimplePageController::transparency

charter:
    path: /charter
    controller: App\Controller\SimplePageController::charter
