index:
    path: /{_locale}{trailingSlash}
    controller: App\Controller\DefaultController::index
    requirements:
        _locale: '%app.locales%'
        trailingSlash : "[/]{0,1}"
    defaults:
        _locale: '%locale%'
        trailingSlash : "/"
