index:
    path: /{trailingSlash}
    controller: App\Controller\SimplePageController::index
    requirements:
        trailingSlash : "[/]{0,1}"
    defaults:
        trailingSlash : "/"

root:
    path: /
    controller: App\Controller\SimplePageController::index
    options: { i18n: false }

suchpage:
    path: /{_locale}/suchpage/
    controller: App\Controller\SimplePageController::such
    requirements:
        maw: '%app.locales%'
    defaults:
        _locale: '%locale%'